spring:
  config:
    activate:
      on-profile: prod

build:
  version: "loan-1.3"

loan:
  message: "Welcome to loan Microservice Prod API"
  contactDetails:
    email: "0fX2I@example.com"
    name: "Loans Team"
  onCallSupport:
    - (555) 555-5555
    - (242) 424-2424