spring:
  application:
    name: "configserver"
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: "file:///D:/WorkSpace/SpringBootKubernetes/section6/v2-spring-cloud-config/file-system-config"
#          search-locations: "classpath:/config"



server:
  port: 8071
encrypt:
  key: "12345678901234567890123456789012"
