spring:
  config:
    activate:
      on-profile: prod

build:
  version: "1.0"

account:
  message: "Welcome to Accounts Microservice Prod API"
  contactDetails:
    email: "0fX2I@example.com"
    name: "Accounts Team"
  onCallSupport:
    - (555) 555-5555
    - (242) 424-2424