services:
  accounts:
    image: "john3kuae/account:s4"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - john3kuae
  loans:
    image: "john3kuae/loan:s4"
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - john3kuae
  cards:
    image: "john3kuae/card:s4"
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - john3kuae
networks:
  john3kuae:
    driver: "bridge"