spring:
  config:
    activate:
      on-profile: qa

build:
  version: "card-1.2"

card:
  message: "Welcome to Card Microservice QA API"
  contactDetails:
    email: "0fX2I@example.com"
    name: "Cards Team"
  onCallSupport:
    - (555) 555-5555
    - (242) 424-2424
