spring:
  config:
    activate:
      on-profile: prod

build:
  version: "card-1.3"

card:
  message: "Welcome to Card Microservice Prod API"
  contactDetails:
    email: "0fX2I@example.com"
    name: "Cards Team"
  onCallSupport:
    - (555) 555-5555
    - (242) 424-2424