spring:
  application:
    name: "configserver"
  profiles:
#    active: native
    active: git
  cloud:
    config:
      server:
#        native:
#          search-locations: "file:///D:/WorkSpace/SpringBootKubernetes/section6/v2-spring-cloud-config/file-system-config"
#          search-locations: "classpath:/config"
        git:
          uri: "https://github.com/boonkuaeb/eazybytes-config.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true


management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
encrypt:
  key: "5bded8e387b6303a1ce5300f41926327711c6a96c82d14d166cbdb471a26583e"
server:
  port: 8071

